import socket
import threading

# ── STEP 1: Storage ──
# To keep findings in memory before writing to disk
scan_results = []

# You can add more targets here
targets = ["scanme.nmap.org", "google.com", "bing.com"]
ports = [22, 80, 443]


# ── STEP 2: Scanning Function ──
def scan_and_log(ip, port):
    try:
        s = socket.socket()
        s.settimeout(1.5)
        # connect_ex returns 0 if the port is open
        if s.connect_ex((ip, port)) == 0:
            result_str = f"[+] {ip}:{port} is OPEN"
            scan_results.append(result_str)  # Save to our list
            print(result_str)
        s.close()
    except:
        pass


# ── STEP 3: File Writing Function ──
def generate_report():
    print(f"\n[*] Finalizing scan... Writing data to file.")
    # 'w' means write mode (creates scan_report.txt)
    with open("scan_report.txt", "w") as f:
        f.write("========================================\n")
        f.write("   PHASE 1: AUTOMATED SECURITY REPORT   \n")
        f.write("========================================\n")
        f.write(f"Targets Scanned: {', '.join(targets)}\n")
        f.write("-" * 40 + "\n")

        if not scan_results:
            f.write("No open ports were found during this session.\n")
        else:
            for line in scan_results:
                f.write(line + "\n")

        f.write("-" * 40 + "\n")
        f.write("End of Report. Generated by Edward's Scanner.\n")
    print(f"[!] Report successfully saved as 'scan_report.txt'")


# ── STEP 4: Orchestration ──
if __name__ == "__main__":
    threads = []
    print(f"--- Project 15: Final Phase 1 Audit ---\n")

    for target in targets:
        for port in ports:
            t = threading.Thread(target=scan_and_log, args=(target, port))
            threads.append(t)
            t.start()

    # Join all threads to ensure scanning is finished
    for t in threads:
        t.join()

    # Finally, write the results to a file
    generate_report()